/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    'payload-mcp-api-keys': PayloadMcpApiKeyAuthOperations;
  };
  blocks: {};
  collections: {
    news: News;
    divisions: Division;
    brands: Brand;
    pages: Page;
    partners: Partner;
    contacts: Contact;
    media: Media;
    products: Product;
    series: Series;
    documents: Document;
    'bc-imports': BcImport;
    users: User;
    redirects: Redirect;
    'payload-mcp-api-keys': PayloadMcpApiKey;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    brands: {
      series: 'series';
    };
    products: {
      documents: 'documents';
    };
    series: {
      products: 'products';
      documents: 'documents';
    };
  };
  collectionsSelect: {
    news: NewsSelect<false> | NewsSelect<true>;
    divisions: DivisionsSelect<false> | DivisionsSelect<true>;
    brands: BrandsSelect<false> | BrandsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    contacts: ContactsSelect<false> | ContactsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    series: SeriesSelect<false> | SeriesSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    'bc-imports': BcImportsSelect<false> | BcImportsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'payload-mcp-api-keys': PayloadMcpApiKeysSelect<false> | PayloadMcpApiKeysSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    homepage: Homepage;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | PayloadMcpApiKey;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface PayloadMcpApiKeyAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Koncept = rozpracováno. Publikováno s datem v budoucnu = Naplánováno – na webu se objeví v daný den a hodinu.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  title: string;
  /**
   * Část URL. Když necháte prázdné, vytvoří se z názvu.
   */
  slug?: string | null;
  /**
   * Datum v budoucnu = článek se zveřejní automaticky v tento čas.
   */
  publishedAt: string;
  state?: string | null;
  category?: ('novinka' | 'veletrh' | 'skoleni' | 'informace') | null;
  division?: (number | null) | Division;
  /**
   * 1–2 věty do výpisu a na úvodní stránku.
   */
  perex: string;
  image?: (number | null) | Media;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * např. fotoreport nebo leták v PDF
   */
  attachments?: (number | Document)[] | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * Produktové divize podle materiálu. Novou divizi můžete založit sami.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "divisions".
 */
export interface Division {
  id: number;
  name: string;
  /**
   * Část URL. Když necháte prázdné, vytvoří se z názvu.
   */
  slug?: string | null;
  status?: ('active' | 'upcoming' | 'hidden') | null;
  order?: number | null;
  /**
   * Jedna až dvě věty – zobrazí se na kartě divize a pod nadpisem.
   */
  perex: string;
  image?: (number | null) | Media;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  catalogDocument?: (number | null) | Document;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Krátký popis pro nevidomé a vyhledávače, např. „Mosazná svěrná spojka BA 32“.
   */
  alt: string;
  sourceUrl?: string | null;
  prefix?: string | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Technické listy, certifikáty, prohlášení o shodě, návody a videa. Přiřaďte je k řadám nebo produktům – zobrazí se u nich na webu.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  title: string;
  type: 'katalog' | 'letak' | 'tl' | 'cert' | 'shoda' | 'navod' | 'video' | 'jine';
  /**
   * např. 2026/03
   */
  edition?: string | null;
  /**
   * Pro videa (YouTube…) nebo dokument uložený jinde. U nahraného souboru nechte prázdné.
   */
  externalUrl?: string | null;
  issuedAt?: string | null;
  /**
   * U certifikátů – 60 dní před koncem platnosti se dokument objeví v upozornění na nástěnce.
   */
  validUntil?: string | null;
  expiry?: string | null;
  series?: (number | Series)[] | null;
  products?: (number | Product)[] | null;
  /**
   * Prázdné = všechny divize
   */
  divisions?: (number | Division)[] | null;
  brands?: (number | Brand)[] | null;
  showInLibrary?: boolean | null;
  sourceUrl?: string | null;
  featured?: boolean | null;
  prefix?: string | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Popis řady a společné parametry (PN, těsnění, normy) se vyplňují jednou za celou řadu.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "series".
 */
export interface Series {
  id: number;
  name: string;
  /**
   * Podle tohoto kódu import přiřadí nové položky k řadě.
   */
  bcCode?: string | null;
  /**
   * Část URL. Když necháte prázdné, vytvoří se z názvu.
   */
  slug?: string | null;
  order?: number | null;
  division: number | Division;
  brand: number | Brand;
  /**
   * Zobrazí se v seznamu řad, např. „Svěrné spojky pro PE trubky 20–110 mm · voda, plyn“.
   */
  summary: string;
  /**
   * např. „Valvopat – mosazné svěrné spojky pro PE trubky 20–110 mm“. Když chybí, použije se název.
   */
  title?: string | null;
  lead?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * např. „Voda · Plyn“
   */
  media?: string | null;
  image?: (number | null) | Media;
  /**
   * Platí pro všechny položky řady – PN, těsnění, normy, médium, teplota, materiál… Zvýrazněné se ukážou v souhrnu u produktu.
   */
  commonParams?:
    | {
        label: string;
        value: string;
        highlight?: boolean | null;
        id?: string | null;
      }[]
    | null;
  dimensionLabel?: string | null;
  dimensionUnit?: string | null;
  threadLabel?: string | null;
  /**
   * Číselník tvarů pro filtr, např. A = vnější závit.
   */
  shapes?:
    | {
        code: string;
        label: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  products?: {
    docs?: (number | Product)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  documents?: {
    docs?: (number | Document)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * Zastoupení výrobci. Divize značky se odvozují z jejích řad.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands".
 */
export interface Brand {
  id: number;
  name: string;
  /**
   * Část URL. Když necháte prázdné, vytvoří se z názvu.
   */
  slug?: string | null;
  order?: number | null;
  /**
   * např. Valvosanitaria Bugatti S.p.A.
   */
  manufacturer?: string | null;
  description: string;
  logo?: (number | null) | Media;
  website?: string | null;
  series?: {
    docs?: (number | Series)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * Kód, název, EAN, MJ a stav přicházejí z importu z BC a nelze je měnit. Fotky, parametry a dokumenty doplňujete zde.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  code: string;
  name: string;
  /**
   * např. „Spojka s vnějším závitem“
   */
  subtitle?: string | null;
  /**
   * Delší text na stránce položky. Odstavce oddělte prázdným řádkem.
   */
  description?: string | null;
  series?: (number | null) | Series;
  /**
   * První fotka je hlavní.
   */
  images?: (number | Media)[] | null;
  /**
   * Kód z číselníku tvarů řady, např. A, O, IM.
   */
  shape?: string | null;
  /**
   * Číslo v jednotkách řady, např. 32 (mm).
   */
  dimension?: number | null;
  /**
   * např. 1/2"
   */
  thread?: string | null;
  /**
   * Pro rozcestník „Vyberte typ výrobku“ – typy se generují z hodnot tohoto pole (např. Svěrné spojky, Kulové kohouty).
   */
  productType?: string | null;
  /**
   * Jen parametry specifické pro položku. Společné parametry se berou z řady. Prázdné se nezobrazí.
   */
  params?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Dokumenty přiřazujete v Knihovně dokumentů. U produktu se zobrazí i dokumenty jeho řady.
   */
  documents?: {
    docs?: (number | Document)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  ean?: string | null;
  unit?: string | null;
  bcSeriesCode?: string | null;
  bcStatus?: ('active' | 'sale' | 'inactive') | null;
  /**
   * Položka, která v importu chyběla, se skryje (nesmaže).
   */
  bcActive?: boolean | null;
  lastImportedAt?: string | null;
  /**
   * Položka se zobrazí jen když má fotku, parametry a řadu a je aktivní v BC.
   */
  showOnWeb?: boolean | null;
  isPublished?: boolean | null;
  contentComplete?: boolean | null;
  missing?: ('photo' | 'params' | 'series')[] | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * Textové stránky – O firmě, Pro partnery, obchodní podmínky, ochrana osobních údajů…
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Část URL. Když necháte prázdné, vytvoří se z názvu.
   */
  slug?: string | null;
  eyebrow?: string | null;
  lead?: string | null;
  layout?:
    | (
        | {
            text: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            image?: (number | null) | Media;
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'content';
          }
        | {
            items?:
              | {
                  title: string;
                  text: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cards';
          }
        | {
            images: (number | Media)[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
      )[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  name: string;
  /**
   * Ulice č., PSČ Obec
   */
  address: string;
  region:
    | 'praha'
    | 'stredocesky-kraj'
    | 'jihocesky-kraj'
    | 'plzensky-kraj'
    | 'karlovarsky-kraj'
    | 'ustecky-kraj'
    | 'liberecky-kraj'
    | 'kralovehradecky-kraj'
    | 'pardubicky-kraj'
    | 'vysocina'
    | 'moravskoslezsky-kraj'
    | 'olomoucky-kraj'
    | 'zlinsky-kraj'
    | 'jihomoravsky-kraj'
    | 'bratislavsky-kraj'
    | 'trnavsky-kraj'
    | 'trenciansky-kraj'
    | 'nitransky-kraj'
    | 'banskobystricky-kraj'
    | 'zilinsky-kraj'
    | 'presovsky-kraj'
    | 'kosicky-kraj';
  phone?: string | null;
  web?: string | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts".
 */
export interface Contact {
  id: number;
  name: string;
  role: string;
  phone?: string | null;
  email?: string | null;
  photo?: (number | null) | Media;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * Nahrajte export položek z Business Central (XLSX nebo CSV). Uvidíte, co je nové, co se změnilo a co se skryje. Změny se zapíšou až po kliknutí na Potvrdit.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bc-imports".
 */
export interface BcImport {
  id: number;
  status?: ('draft' | 'confirmed' | 'superseded' | 'failed') | null;
  summary?: {
    created?: number | null;
    changed?: number | null;
    hidden?: number | null;
    unchanged?: number | null;
  };
  diff?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  rows?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  errors?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  columns?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  uploadedBy?: (number | null) | User;
  confirmedBy?: (number | null) | User;
  confirmedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Nový účet: vyplňte e-mail, jméno a roli, heslo zadejte libovolné dočasné. Uživateli hned přijde e-mail, kde si nastaví vlastní heslo.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Editor: aktuality a texty. Správce katalogu: navíc produkty, řady, dokumenty a import z BC. Admin: vše včetně uživatelů.
   */
  role: 'editor' | 'catalog' | 'admin';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Mapa starých URL z profispojky.cz na nové stránky (301). Zadejte cestu bez domény, např. /download.php?fid=1503.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'series';
          value: number | Series;
        } | null)
      | ({
          relationTo: 'products';
          value: number | Product;
        } | null)
      | ({
          relationTo: 'news';
          value: number | News;
        } | null)
      | ({
          relationTo: 'divisions';
          value: number | Division;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * API keys control which collections, resources, tools, and prompts MCP clients can access
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys".
 */
export interface PayloadMcpApiKey {
  id: number;
  /**
   * The user that the API key is associated with.
   */
  user: number | User;
  /**
   * A useful label for the API key.
   */
  label?: string | null;
  /**
   * The purpose of the API key.
   */
  description?: string | null;
  news?: {
    /**
     * Allow clients to find news.
     */
    find?: boolean | null;
    /**
     * Allow clients to create news.
     */
    create?: boolean | null;
    /**
     * Allow clients to update news.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete news.
     */
    delete?: boolean | null;
  };
  pages?: {
    /**
     * Allow clients to find pages.
     */
    find?: boolean | null;
    /**
     * Allow clients to create pages.
     */
    create?: boolean | null;
    /**
     * Allow clients to update pages.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete pages.
     */
    delete?: boolean | null;
  };
  divisions?: {
    /**
     * Allow clients to find divisions.
     */
    find?: boolean | null;
    /**
     * Allow clients to create divisions.
     */
    create?: boolean | null;
    /**
     * Allow clients to update divisions.
     */
    update?: boolean | null;
  };
  brands?: {
    /**
     * Allow clients to find brands.
     */
    find?: boolean | null;
    /**
     * Allow clients to create brands.
     */
    create?: boolean | null;
    /**
     * Allow clients to update brands.
     */
    update?: boolean | null;
  };
  series?: {
    /**
     * Allow clients to find series.
     */
    find?: boolean | null;
    /**
     * Allow clients to create series.
     */
    create?: boolean | null;
    /**
     * Allow clients to update series.
     */
    update?: boolean | null;
  };
  products?: {
    /**
     * Allow clients to find products.
     */
    find?: boolean | null;
    /**
     * Allow clients to update products.
     */
    update?: boolean | null;
  };
  documents?: {
    /**
     * Allow clients to find documents.
     */
    find?: boolean | null;
    /**
     * Allow clients to create documents.
     */
    create?: boolean | null;
    /**
     * Allow clients to update documents.
     */
    update?: boolean | null;
  };
  partners?: {
    /**
     * Allow clients to find partners.
     */
    find?: boolean | null;
    /**
     * Allow clients to create partners.
     */
    create?: boolean | null;
    /**
     * Allow clients to update partners.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete partners.
     */
    delete?: boolean | null;
  };
  contacts?: {
    /**
     * Allow clients to find contacts.
     */
    find?: boolean | null;
    /**
     * Allow clients to create contacts.
     */
    create?: boolean | null;
    /**
     * Allow clients to update contacts.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete contacts.
     */
    delete?: boolean | null;
  };
  redirects?: {
    /**
     * Allow clients to find redirects.
     */
    find?: boolean | null;
    /**
     * Allow clients to create redirects.
     */
    create?: boolean | null;
    /**
     * Allow clients to update redirects.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete redirects.
     */
    delete?: boolean | null;
  };
  media?: {
    /**
     * Allow clients to find media.
     */
    find?: boolean | null;
    /**
     * Allow clients to update media.
     */
    update?: boolean | null;
  };
  bcImports?: {
    /**
     * Allow clients to find bc-imports.
     */
    find?: boolean | null;
  };
  homepage?: {
    /**
     * Allow clients to find homepage global.
     */
    find?: boolean | null;
    /**
     * Allow clients to update homepage global.
     */
    update?: boolean | null;
  };
  siteSettings?: {
    /**
     * Allow clients to find site-settings global.
     */
    find?: boolean | null;
    /**
     * Allow clients to update site-settings global.
     */
    update?: boolean | null;
  };
  'payload-mcp-tool'?: {
    /**
     * Fronta „Doplnit obsah“: položky z BC, kterým chybí fotka, parametry nebo řada (na webu se nezobrazují).
     */
    contentQueue?: boolean | null;
    /**
     * Dokumenty (certifikáty…), jejichž platnost vyprší do 60 dnů nebo už vypršela.
     */
    expiringDocuments?: boolean | null;
    /**
     * Souhrn katalogu: počty položek publikovaných / ve frontě / skrytých a poslední import z BC.
     */
    catalogStats?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  hasAPIKey?: boolean | null;
  collection: 'payload-mcp-api-keys';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'divisions';
        value: number | Division;
      } | null)
    | ({
        relationTo: 'brands';
        value: number | Brand;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null)
    | ({
        relationTo: 'contacts';
        value: number | Contact;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'series';
        value: number | Series;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'bc-imports';
        value: number | BcImport;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  publishedAt?: T;
  state?: T;
  category?: T;
  division?: T;
  perex?: T;
  image?: T;
  body?: T;
  attachments?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "divisions_select".
 */
export interface DivisionsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  status?: T;
  order?: T;
  perex?: T;
  image?: T;
  body?: T;
  catalogDocument?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands_select".
 */
export interface BrandsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  order?: T;
  manufacturer?: T;
  description?: T;
  logo?: T;
  website?: T;
  series?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  eyebrow?: T;
  lead?: T;
  layout?:
    | T
    | {
        content?:
          | T
          | {
              text?: T;
              image?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        cards?:
          | T
          | {
              items?:
                | T
                | {
                    title?: T;
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              images?: T;
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  name?: T;
  address?: T;
  region?: T;
  phone?: T;
  web?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts_select".
 */
export interface ContactsSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  phone?: T;
  email?: T;
  photo?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  sourceUrl?: T;
  prefix?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  code?: T;
  name?: T;
  subtitle?: T;
  description?: T;
  series?: T;
  images?: T;
  shape?: T;
  dimension?: T;
  thread?: T;
  productType?: T;
  params?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  documents?: T;
  ean?: T;
  unit?: T;
  bcSeriesCode?: T;
  bcStatus?: T;
  bcActive?: T;
  lastImportedAt?: T;
  showOnWeb?: T;
  isPublished?: T;
  contentComplete?: T;
  missing?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "series_select".
 */
export interface SeriesSelect<T extends boolean = true> {
  name?: T;
  bcCode?: T;
  slug?: T;
  order?: T;
  division?: T;
  brand?: T;
  summary?: T;
  title?: T;
  lead?: T;
  description?: T;
  media?: T;
  image?: T;
  commonParams?:
    | T
    | {
        label?: T;
        value?: T;
        highlight?: T;
        id?: T;
      };
  dimensionLabel?: T;
  dimensionUnit?: T;
  threadLabel?: T;
  shapes?:
    | T
    | {
        code?: T;
        label?: T;
        description?: T;
        id?: T;
      };
  products?: T;
  documents?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  title?: T;
  type?: T;
  edition?: T;
  externalUrl?: T;
  issuedAt?: T;
  validUntil?: T;
  expiry?: T;
  series?: T;
  products?: T;
  divisions?: T;
  brands?: T;
  showInLibrary?: T;
  sourceUrl?: T;
  featured?: T;
  prefix?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bc-imports_select".
 */
export interface BcImportsSelect<T extends boolean = true> {
  status?: T;
  summary?:
    | T
    | {
        created?: T;
        changed?: T;
        hidden?: T;
        unchanged?: T;
      };
  diff?: T;
  rows?: T;
  errors?: T;
  columns?: T;
  uploadedBy?: T;
  confirmedBy?: T;
  confirmedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys_select".
 */
export interface PayloadMcpApiKeysSelect<T extends boolean = true> {
  user?: T;
  label?: T;
  description?: T;
  news?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  pages?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  divisions?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
      };
  brands?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
      };
  series?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
      };
  products?:
    | T
    | {
        find?: T;
        update?: T;
      };
  documents?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
      };
  partners?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  contacts?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  redirects?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  media?:
    | T
    | {
        find?: T;
        update?: T;
      };
  bcImports?:
    | T
    | {
        find?: T;
      };
  homepage?:
    | T
    | {
        find?: T;
        update?: T;
      };
  siteSettings?:
    | T
    | {
        find?: T;
        update?: T;
      };
  'payload-mcp-tool'?:
    | T
    | {
        contentQueue?: T;
        expiringDocuments?: T;
        catalogStats?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  hasAPIKey?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  eyebrow?: string | null;
  title: string;
  lead?: string | null;
  stats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  heroImages?: (number | Media)[] | null;
  featuredSeries?: (number | null) | Series;
  featuredText?: string | null;
  usps?:
    | {
        icon?: ('clock' | 'file' | 'pin' | 'tool' | 'check' | 'phone' | 'box') | null;
        text: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  phone: string;
  phone2?: string | null;
  email: string;
  email2?: string | null;
  hours?: string | null;
  warehouseStreet?: string | null;
  warehouseCity?: string | null;
  companyName?: string | null;
  seat?: string | null;
  ico?: string | null;
  dic?: string | null;
  registry?: string | null;
  footerLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  lead?: T;
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  heroImages?: T;
  featuredSeries?: T;
  featuredText?: T;
  usps?:
    | T
    | {
        icon?: T;
        text?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  phone?: T;
  phone2?: T;
  email?: T;
  email2?: T;
  hours?: T;
  warehouseStreet?: T;
  warehouseCity?: T;
  companyName?: T;
  seat?: T;
  ico?: T;
  dic?: T;
  registry?: T;
  footerLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}